import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { title } from "process";
import SearchBar from "@/components/Search";
import { Box } from "@chakra-ui/react";
import WeatherCard from "@/components/Card";

export default function Home() {
  const myStyle = {
    backgroundColor: "orange",
    minHeight: "100vh",
  };
  return (
    <div className={styles.container} style={myStyle}>
      <Head>
        <title>Weather App</title>
        <meta
          name="An app showing weather details"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <SearchBar />
      </Box>
    </div>
  );
}
